<?php


$synonyms = [
    // Шины (Tyres)
    'pirelli'      => ['pirelli', 'пирелли', 'пирели', 'пирэлли', 'пирелi', 'пирелiй'],
    'nokian'       => ['nokian', 'нокиан', 'нокиян', 'нокiан'],
    'michelin'     => ['michelin', 'мишлен', 'мишленн', 'мишелин'],
    'cordiant'     => ['cordiant', 'кордиант', 'кордиант'],
    'bridgestone'  => ['bridgestone', 'бриджстоун', 'бридж', 'брiджстоун'],
    'continental'  => ['continental', 'континенталь', 'континентал', 'контiнентал'],
    'goodyear'     => ['goodyear', 'гудиер', 'гудьер', 'гудйер'],
    'hankook'      => ['hankook', 'ханкук', 'ханкок', 'ханкук'],
    'yokohama'     => ['yokohama', 'ёкохама', 'йокогама', 'йокохама', 'йокахама'],
    'dunlop'       => ['dunlop', 'данлоп', 'данлап', 'данлоп'],
    'kumho'        => ['kumho', 'кумхо', 'кумо'],
    'maxxis'       => ['maxxis', 'максис', 'максiс'],
    'matador'      => ['matador', 'матадор'],
    'triangle'     => ['triangle', 'триангл', 'триангле', 'триангл'],
    'gislaved'     => ['gislaved', 'гиславед'],
    'nexen'        => ['nexen', 'нексен', 'нексе'],
    'sava'         => ['sava', 'сава'],
    'viatti'       => ['viatti', 'виатти', 'виати'],
    'amtel'        => ['amtel', 'амтел', 'амтэл'],
    'toyo'         => ['toyo', 'тойо', 'тоё'],
    'falken'       => ['falken', 'фалкен', 'фалкен'],
    'federal'      => ['federal', 'федерал'],
    'barum'        => ['barum', 'барум'],
    'sailun'       => ['sailun', 'сайлун', 'сайлон', 'сайлун'],
    'firestone'    => ['firestone', 'файрстоун', 'файерстоун'],
    'aurora'       => ['aurora', 'аурора'],
    'bfgoodrich'   => ['bfgoodrich', 'бфгудрич', 'бф гудрич', 'бфг'],
    'rosava'       => ['rosava', 'росава'],
    'petlas'       => ['petlas', 'петлас'],
    'linglong'     => ['linglong', 'линглонг', 'линг лонг'],
    'kama'         => ['kama', 'кама'],
    'nordman'      => ['nordman', 'нордман', 'нордмэн'],
    'premiorri'    => ['premiorri', 'премиорри'],
    'roadstone'    => ['roadstone', 'роудстоун', 'роадстоун'],
    'sunfull'      => ['sunfull', 'санфул', 'санфулл'],
    'sunny'        => ['sunny', 'санни', 'сани'],
    'tunga'        => ['tunga', 'тунга'],
    'jinhu'        => ['jinhu', 'джинху'],
    'goodride'     => ['goodride', 'гудрайд', 'гудрайт'],
    'atlanta'      => ['atlanta', 'атланта'],
    'doublecoin'   => ['doublecoin', 'даблкоин', 'дабл коин'],
    'triangle'     => ['triangle', 'триангл', 'триангле'],
    'sava'         => ['sava', 'сава'],
    'debica'       => ['debica', 'дебика'],
    'delinte'      => ['delinte', 'делинте'],
    'zeetex'       => ['zeetex', 'зитекс', 'зетекс'],
    'westlake'     => ['westlake', 'вестлейк', 'вестлейк'],
    'mirage'       => ['mirage', 'мираж'],
    'opir'         => ['opir', 'опир'],
    'roadcruza'    => ['roadcruza', 'роудкруза'],

    // Диски (Wheels)
    'kosei'        => ['kosei', 'косей'],
    'bk'           => ['bk', 'бк'],
    'alcasta'      => ['alcasta', 'алкаста'],
    'advanti'      => ['advanti', 'адванти'],
    'replay'       => ['replay', 'реплей', 'реплай'],
    'tech line'    => ['tech line', 'техлайн', 'течлайн', 'techline'],
    'skad'         => ['skad', 'скад'],
    'yokatta'      => ['yokatta', 'йокатта', 'йокката'],
    'sakura'       => ['sakura', 'сакура'],
    'nitro'        => ['nitro', 'нитро'],
    'enzo'         => ['enzo', 'энцо', 'енцо'],
    'alutec'       => ['alutec', 'алутек'],
    'rossen'       => ['rossen', 'россен', 'росен'],
    'pdw'          => ['pdw', 'пдв'],
    'rs wheels'    => ['rs wheels', 'рс', 'рс вилз', 'рс уилс'],
    'zw'           => ['zw', 'зедабл', 'зедабл в'],
    'disla'        => ['disla', 'дисла'],
    'ls wheels'    => ['ls wheels', 'лс', 'лс вилз', 'лс уилс'],
    'kei'          => ['kei', 'кей'],
    'original'     => ['original', 'оригинал'],
    'cms'          => ['cms', 'цмс'],
    'mak'          => ['mak', 'мак'],
    'replika'      => ['replika', 'реплика', 'репліка'],

    // АКБ (Batteries)
    'varta'        => ['varta', 'варта', 'Варта'],
    'bosch'        => ['bosch', 'бош', 'бошь', 'бош'],
    'tudor'        => ['tudor', 'тудор'],
    'mutlu'        => ['mutlu', 'мутлу'],
    'topla'        => ['topla', 'топла'],
    'zubr'         => ['zubr', 'зубр'],
    'bars'         => ['bars', 'барс'],
    'aktech'       => ['aktech', 'актех', 'ак тех'],
    'exide'        => ['exide', 'эксайд', 'ексайд'],
    'tab'          => ['tab', 'таб'],
    'rocket'       => ['rocket', 'рокет', 'рокэт'],
    'fireball'     => ['fireball', 'фаербол', 'файербол'],
    'alpha line'   => ['alpha line', 'альфа лайн'],
    'ista'         => ['ista', 'иста'],
    'medalist'     => ['medalist', 'медалист'],
    'solite'       => ['solite', 'солайт', 'солит'],
    'delkor'       => ['delkor', 'делкор'],
    'tornado'      => ['tornado', 'торнадо'],
    'westa'        => ['westa', 'веста', 'вэста'],
    'energizer'    => ['energizer', 'энерджайзер'],
    'mol'          => ['mol', 'мол'],
    'istanbul'     => ['istanbul', 'истанбул', 'истамбул'],
    'titan'        => ['titan', 'титан'],
    'svet'         => ['svet', 'свет'],
    'akome'        => ['akome', 'аком', 'акоме'],
    'forse'        => ['forse', 'форсе', 'форс'],
    'volat'        => ['volat', 'волат'],
    'beast'        => ['beast', 'бист', 'бисть'],
    'ursa'         => ['ursa', 'урса'],
    'meda'         => ['meda', 'меда'],
    'prestige'     => ['prestige', 'престиж'],
    'fiamm'        => ['fiamm', 'фиамм', 'фиам'],
    'tiger'        => ['tiger', 'тигр', 'тайгер'],
];



$carBrandSynonyms = [
    // Российские и СНГ
    'lada' => ['лада', 'lada', 'LADA', 'Lada', 'ВАЗ', 'ваз', 'VAZ'],
    'uaz' => ['уаз', 'uaz', 'UAZ', 'УАЗ'],
    'gaz' => ['газ', 'gaz', 'GAZ', 'ГАЗ'],
    'kamaz' => ['камаз', 'kamaz', 'KAMAZ', 'Камаз'],
    'zil' => ['зил', 'zil', 'ЗИЛ', 'ZIL'],
    'moskvich' => ['москвич', 'moskvich', 'Moskvich', 'Москвич'],
    'volga' => ['волга', 'volga', 'Volga', 'Волга'],
    'raf' => ['раф', 'raf', 'RAF', 'Раф'],
    'tagaz' => ['тагаз', 'tagaz', 'TagAZ', 'ТагАЗ'],
    'derways' => ['дервейс', 'derways', 'Derways', 'Дервейс'],
    'seaz' => ['сеаз', 'seaz', 'SEAZ', 'СеАЗ'],
    'izh' => ['иж', 'izh', 'IZH', 'ИЖ'],
    // Япония
    'toyota' => ['тойота', 'toyota', 'Toyota', 'ТОЙОТА'],
    'nissan' => ['ниссан', 'nissan', 'Nissan', 'НИССАН'],
    'honda' => ['хонда', 'honda', 'Honda', 'ХОНДА'],
    'mitsubishi' => ['митсубиси', 'mitsubishi', 'Mitsubishi', 'МИТСУБИСИ'],
    'subaru' => ['субару', 'subaru', 'Subaru', 'СУБАРУ'],
    'mazda' => ['мазда', 'mazda', 'Mazda', 'МАЗДА'],
    'suzuki' => ['сузуки', 'suzuki', 'Suzuki', 'СУЗУКИ'],
    'lexus' => ['лексус', 'lexus', 'Lexus', 'ЛЕКСУС'],
    'infiniti' => ['инфинити', 'infiniti', 'Infiniti', 'ИНФИНИТИ'],
    'daihatsu' => ['дайхатсу', 'daihatsu', 'Daihatsu', 'ДАЙХАТСУ'],
    'acura' => ['акура', 'acura', 'Acura', 'АКУРА'],
    'isuzu' => ['исузу', 'isuzu', 'Isuzu', 'ИСУЗУ'],
    'hino' => ['хино', 'hino', 'Hino', 'ХИНО'],
    // Корея
    'kia' => ['киа', 'kia', 'KIA', 'Киа'],
    'hyundai' => ['хендэ', 'хендай', 'hyundai', 'Hyundai', 'Хендай', 'Хёндэ'],
    'genesis' => ['генезис', 'genesis', 'Genesis', 'ГЕНЕЗИС'],
    'ssangyong' => ['сангйонг', 'ssangyong', 'SsangYong', 'ССАНГЙОНГ', 'Ссангйонг'],
    'daewoo' => ['дэу', 'daewoo', 'Daewoo', 'ДЭУ', 'Дэу'],
    'ravon' => ['равон', 'ravon', 'Ravon', 'РАВОН'],
    // Германия
    'mercedes-benz' => ['mercedes', 'mercedes-benz', 'мерседес', 'мерседес-бенц', 'Mercedes', 'Mercedes-Benz', 'Мерседес', 'Mercedes Benz', 'Мерс'],
    'bmw' => ['бмв', 'bmw', 'BMW', 'БМВ'],
    'audi' => ['ауди', 'audi', 'Audi', 'АУДИ'],
    'volkswagen' => ['фольксваген', 'volkswagen', 'Volkswagen', 'VW', 'vw', 'Фольксваген', 'Вольксваген', 'ВВ'],
    'opel' => ['опель', 'opel', 'Opel', 'ОПЕЛЬ'],
    'porsche' => ['порше', 'porsche', 'Porsche', 'ПОРШЕ'],
    'smart' => ['смарт', 'smart', 'Smart', 'Смарт'],
    'maybach' => ['майбах', 'maybach', 'Maybach', 'МАЙБАХ'],
    'man' => ['man', 'MAN', 'Ман', 'МАН'],
    'borgward' => ['боргвард', 'borgward', 'Borgward', 'БОРГВАРД'],
    // Франция
    'renault' => ['рено', 'renault', 'Renault', 'РЕНО'],
    'peugeot' => ['пежо', 'peugeot', 'Peugeot', 'ПЕЖО'],
    'citroen' => ['ситроен', 'citroen', 'Citroen', 'СИТРОЕН', 'Ситроэн'],
    // Италия
    'fiat' => ['фиат', 'fiat', 'Fiat', 'ФИАТ'],
    'alfa romeo' => ['альфа ромео', 'alfa romeo', 'Alfa Romeo', 'АЛЬФА РОМЕО', 'Альфа-Ромео'],
    'lancia' => ['ланча', 'lancia', 'Lancia', 'ЛАНЧА', 'Лянча'],
    'maserati' => ['масерати', 'maserati', 'Maserati', 'МАСЕРАТИ'],
    'ferrari' => ['феррари', 'ferrari', 'Ferrari', 'ФЕРРАРИ'],
    'lamborghini' => ['ламборгини', 'lamborghini', 'Lamborghini', 'ЛАМБОРГИНИ'],
    'iveco' => ['ивеко', 'iveco', 'Iveco', 'ИВЕКО'],
    // США
    'ford' => ['форд', 'ford', 'Ford', 'ФОРД'],
    'chevrolet' => ['шевроле', 'chevrolet', 'Chevrolet', 'ШЕВРОЛЕ', 'Шеви', 'Chevy'],
    'cadillac' => ['кадиллак', 'cadillac', 'Cadillac', 'КАДИЛЛАК'],
    'jeep' => ['джип', 'jeep', 'Jeep', 'ДЖИП'],
    'chrysler' => ['крайслер', 'chrysler', 'Chrysler', 'КРАЙСЛЕР'],
    'dodge' => ['додж', 'dodge', 'Dodge', 'ДОДЖ'],
    'gmc' => ['gmc', 'GMC', 'ДжиЭмСи', 'Джи Эм Си'],
    'lincoln' => ['линкольн', 'lincoln', 'Lincoln', 'ЛИНКОЛЬН'],
    'buick' => ['бьюик', 'buick', 'Buick', 'БЬЮИК'],
    'pontiac' => ['понтиак', 'pontiac', 'Pontiac', 'ПОНТИАК'],
    'saturn' => ['сатурн', 'saturn', 'Saturn', 'САТУРН'],
    'hummer' => ['хаммер', 'hummer', 'Hummer', 'ХАММЕР'],
    // Великобритания
    'land rover' => ['ленд ровер', 'land rover', 'Land Rover', 'ЛЕНД РОВЕР', 'Ленд-Ровер', 'Ровер'],
    'jaguar' => ['ягуар', 'jaguar', 'Jaguar', 'ЯГУАР'],
    'mini' => ['мини', 'mini', 'Mini', 'МИНИ'],
    'rolls-royce' => ['роллс-ройс', 'rolls-royce', 'Rolls-Royce', 'РОЛЛС-РОЙС'],
    'bentley' => ['бентли', 'bentley', 'Bentley', 'БЕНТЛИ'],
    'aston martin' => ['астон мартин', 'aston martin', 'Aston Martin', 'АСТОН МАРТИН'],
    'mg' => ['мг', 'mg', 'MG', 'МГ'],
    'lotus' => ['лотус', 'lotus', 'Lotus', 'ЛОТУС'],
    // Швеция
    'volvo' => ['вольво', 'volvo', 'Volvo', 'ВОЛЬВО'],
    'saab' => ['сааб', 'saab', 'Saab', 'СААБ'],
    'scania' => ['скания', 'scania', 'Scania', 'СКАНИЯ'],
    // Чехия
    'skoda' => ['шкода', 'skoda', 'Skoda', 'ШКОДА', 'Шкодa'],
    'tatra' => ['татра', 'tatra', 'Tatra', 'ТАТРА'],
    // Китай
    'geely' => ['джили', 'geely', 'Geely', 'ДЖИЛИ'],
    'chery' => ['черри', 'chery', 'Chery', 'ЧЕРРИ'],
    'haval' => ['хавал', 'haval', 'Haval', 'ХАВАЛ'],
    'lifan' => ['лифан', 'lifan', 'Lifan', 'ЛИФАН'],
    'great wall' => ['great wall', 'грейтуол', 'Great Wall', 'ГРЕЙТ УОЛЛ', 'Грейт Уолл'],
    'exeed' => ['exeed', 'Exeed', 'Эксид', 'Эксид'],
    'jac' => ['jac', 'JAC', 'Джак', 'ЖАК'],
    'byd' => ['byd', 'BYD', 'БИД', 'Байд'],
    'dongfeng' => ['донгфенг', 'dongfeng', 'Dongfeng', 'ДОНГФЕНГ'],
    'changan' => ['чанган', 'changan', 'Changan', 'ЧАНГАН'],
    'faw' => ['фав', 'faw', 'FAW', 'ФАВ'],
    'zotye' => ['зоти', 'zotye', 'Zotye', 'ЗОТИ'],
    'baic' => ['баик', 'baic', 'BAIC', 'БАИК'],
        // Индия
    'mahindra' => ['махиндра', 'mahindra', 'Mahindra', 'МАХИНДРА'],
    'tata' => ['тата', 'tata', 'Tata', 'ТАТА'],
    // Экзотика, электромобили, коммерческие
    'tesla' => ['тесла', 'tesla', 'Tesla', 'ТЕСЛА'],
    'smart' => ['смарт', 'smart', 'Smart', 'Смарт'],
    'bugatti' => ['бугатти', 'bugatti', 'Bugatti', 'БУГАТТИ'],
    'proton' => ['протон', 'proton', 'Proton', 'ПРОТОН'],
    'datsun' => ['датсун', 'datsun', 'Datsun', 'ДАТСУН'],
    'lada vesta' => ['vesta', 'веста', 'Vesta', 'Веста', 'Лада Веста'],
    // Добавьте по необходимости другие бренды из вашей базы
];


$carModelSynonyms = [
    // LADA
    'granta' => ['granta', 'гранта', 'Granta', 'Гранта'],
    'vesta' => ['vesta', 'веста', 'Vesta', 'Веста'],
    'xray' => ['xray', 'иксрей', 'икс-рей', 'XRay', 'XRAY', 'Иксрей'],
    'largus' => ['largus', 'ларгус', 'Largus', 'Ларгус'],
    'kalina' => ['kalina', 'калина', 'Kalina', 'Калина'],
    'priora' => ['priora', 'приора', 'Priora', 'Приора'],
    'samara' => ['samara', 'самара', 'Samara', 'Самара'],
    'niva' => ['niva', 'нива', 'Niva', 'Нива', 'Lada 4x4', 'Лада 4x4'],
    '2110' => ['2110', 'ваз 2110', 'ВАЗ 2110'],
    '2107' => ['2107', 'ваз 2107', 'ВАЗ 2107'],
    '2109' => ['2109', 'ваз 2109', 'ВАЗ 2109'],
    // TOYOTA
    'camry' => ['camry', 'камри', 'Camry', 'Камри'],
    'corolla' => ['corolla', 'королла', 'Corolla', 'Королла'],
    'land cruiser' => ['land cruiser', 'ланд крузер', 'крузак', 'Land Cruiser', 'Ленд Крузер', 'Крузер'],
    'rav4' => ['rav4', 'рав4', 'RAV4', 'Рав4', 'RAV 4', 'Рав 4'],
    'prado' => ['prado', 'прадо', 'Prado', 'Прадо'],
    'hilux' => ['hilux', 'хайлюкс', 'Hilux', 'Хайлюкс'],
    'crown' => ['crown', 'краун', 'Crown', 'Краун'],
    'avensis' => ['avensis', 'авенсис', 'Avensis', 'Авенсис'],
    // NISSAN
    'almera' => ['almera', 'альмера', 'Almera', 'Альмера'],
    'qashqai' => ['qashqai', 'кашкай', 'Qashqai', 'Кашкай'],
    'x-trail' => ['x-trail', 'x trail', 'икстрейл', 'X-Trail', 'X Trail', 'ИксТрейл', 'Икс-Трейл'],
    'teana' => ['teana', 'тиана', 'Teana', 'Тиана'],
    'murano' => ['murano', 'мурано', 'Murano', 'Мурано'],
    'note' => ['note', 'ноут', 'Note', 'Ноут'],
    'juke' => ['juke', 'жук', 'Juke', 'Жук'],
    'patrol' => ['patrol', 'патрол', 'Patrol', 'Патрол'],
    // KIA
    'rio' => ['rio', 'рио', 'Rio', 'Рио'],
    'ceed' => ['ceed', 'сид', 'Ceed', 'Сид'],
    'sportage' => ['sportage', 'спортаж', 'Sportage', 'Спортейдж'],
    'sorento' => ['sorento', 'соренто', 'Sorento', 'Соренто'],
    'optima' => ['optima', 'оптима', 'Optima', 'Оптима'],
    'cerato' => ['cerato', 'церато', 'Cerato', 'Церато'],
    'seltos' => ['seltos', 'селтос', 'Seltos', 'Селтос'],
    // HYUNDAI
    'solaris' => ['solaris', 'солярис', 'Solaris', 'Солярис'],
    'creta' => ['creta', 'крета', 'Creta', 'Крета'],
    'elantra' => ['elantra', 'элантра', 'Elantra', 'Элантра'],
    'tucson' => ['tucson', 'туксон', 'Tucson', 'Туксон'],
    'santa fe' => ['santa fe', 'санта фе', 'Santa Fe', 'Санта Фе'],
    'sonata' => ['sonata', 'соната', 'Sonata', 'Соната'],
    'ix35' => ['ix35', 'ix 35', 'IX35', 'IX 35'],
    // VOLKSWAGEN
    'polo' => ['polo', 'поло', 'Polo', 'Поло'],
    'passat' => ['passat', 'пассат', 'Passat', 'Пассат'],
    'tiguan' => ['tiguan', 'тигуан', 'Tiguan', 'Тигуан'],
    'touareg' => ['touareg', 'туарег', 'Touareg', 'Туарег'],
    'golf' => ['golf', 'гольф', 'Golf', 'Гольф'],
    'jetta' => ['jetta', 'джетта', 'Jetta', 'Джетта'],
    'multivan' => ['multivan', 'мультивэн', 'Multivan', 'Мультивэн', 'Мультиван'],
    // SKODA
    'octavia' => ['octavia', 'октавия', 'Octavia', 'Октавия'],
    'rapid' => ['rapid', 'рапид', 'Rapid', 'Рапид'],
    'kodiaq' => ['kodiaq', 'кодиак', 'Kodiaq', 'Кодиак'],
    'superb' => ['superb', 'суперб', 'Superb', 'Суперб'],
    'fabia' => ['fabia', 'фабия', 'Fabia', 'Фабия'],
    'kamiq' => ['kamiq', 'камик', 'Kamiq', 'Камик'],
    // RENAULT
    'logan' => ['logan', 'логан', 'Logan', 'Логан'],
    'duster' => ['duster', 'дастер', 'Duster', 'Дастер'],
    'sandero' => ['sandero', 'сандеро', 'Sandero', 'Сандеро'],
    'arkana' => ['arkana', 'арканa', 'Arkana', 'Аркана'],
    'kaptur' => ['kaptur', 'каптур', 'Kaptur', 'Каптур'],
    // FORD
    'focus' => ['focus', 'фокус', 'Focus', 'Фокус'],
    'mondeo' => ['mondeo', 'мондео', 'Mondeo', 'Мондео'],
    'fiesta' => ['fiesta', 'фиеста', 'Fiesta', 'Фиеста'],
    'kuga' => ['kuga', 'куга', 'Kuga', 'Куга'],
    'explorer' => ['explorer', 'эксплорер', 'Explorer', 'Эксплорер'],
    // MAZDA
    'mazda 3' => ['mazda 3', 'мазда 3', 'Mazda 3', 'Мазда 3', 'мазда3', 'mazda3'],
    'mazda 6' => ['mazda 6', 'мазда 6', 'Mazda 6', 'Мазда 6', 'мазда6', 'mazda6'],
    'cx-5' => ['cx-5', 'cx 5', 'CX-5', 'CX 5', 'СХ-5', 'СХ 5'],
    'cx-7' => ['cx-7', 'cx 7', 'CX-7', 'CX 7', 'СХ-7', 'СХ 7'],
    // MITSUBISHI
    'outlander' => ['outlander', 'аутлендер', 'Outlander', 'Аутлендер'],
    'lancer' => ['lancer', 'лансер', 'Lancer', 'Лансер'],
    'asx' => ['asx', 'асх', 'ASX', 'АСХ'],
    'pajero' => ['pajero', 'паджеро', 'Pajero', 'Паджеро'],
    // HONDA
    'civic' => ['civic', 'сивик', 'Civic', 'Сивик'],
    'accord' => ['accord', 'аккорд', 'Accord', 'Аккорд'],
    'cr-v' => ['cr-v', 'crv', 'CR-V', 'CRV', 'ЦРВ', 'ЦР-В'],
    'fit' => ['fit', 'фит', 'Fit', 'Фит'],
    // MERCEDES-BENZ
    'c-class' => ['c-class', 'c class', 'c-класс', 'C-Class', 'C Class', 'Ц-Класс', 'Ц класс'],
    'e-class' => ['e-class', 'e class', 'e-класс', 'E-Class', 'E Class', 'Е-Класс', 'Е класс'],
    'glc' => ['glc', 'GLC', 'ГЛЦ', 'ГЛС'],
    'gle' => ['gle', 'GLE', 'ГЛЕ'],
    's-class' => ['s-class', 's class', 'S-Class', 'S Class', 'эс-класс', 'С-класс'],
    // BMW
    '3 series' => ['3 series', '3er', '3-я серия', '3 серия', 'BMW 3', 'BMW 3er', 'e46', 'e90', 'e36'],
    '5 series' => ['5 series', '5er', '5-я серия', '5 серия', 'BMW 5', 'BMW 5er', 'e60', 'e39', 'g30'],
    'x3' => ['x3', 'x 3', 'X3', 'X 3', 'Икс3', 'Икс 3'],
    'x5' => ['x5', 'x 5', 'X5', 'X 5', 'Икс5', 'Икс 5'],
    // AUDI
    'a4' => ['a4', 'a 4', 'A4', 'A 4'],
    'a6' => ['a6', 'a 6', 'A6', 'A 6'],
    'q5' => ['q5', 'q 5', 'Q5', 'Q 5'],
    'q7' => ['q7', 'q 7', 'Q7', 'Q 7'],
    // SUBARU
    'forester' => ['forester', 'форестер', 'Forester', 'Форестер'],
    'outback' => ['outback', 'аутбэк', 'Outback', 'Аутбэк'],
    'impreza' => ['impreza', 'импреза', 'Impreza', 'Импреза'],
    // INFINITI
    'qx50' => ['qx50', 'qx 50', 'QX50', 'QX 50'],
    'qx60' => ['qx60', 'qx 60', 'QX60', 'QX 60'],
    // LEXUS
    'rx' => ['rx', 'RX', 'РХ'],
    'nx' => ['nx', 'NX', 'НХ'],
    'es' => ['es', 'ES', 'ЕС'],
    // PEUGEOT
    '308' => ['308', 'Пежо 308', 'Peugeot 308'],
    '408' => ['408', 'Пежо 408', 'Peugeot 408'],
    '3008' => ['3008', 'Пежо 3008', 'Peugeot 3008'],
    // CITROEN
    'c4' => ['c4', 'c 4', 'C4', 'C 4'],
    'c5' => ['c5', 'c 5', 'C5', 'C 5'],
    // OPEL
    'astra' => ['astra', 'астра', 'Astra', 'Астра'],
    'insignia' => ['insignia', 'инсигния', 'Insignia', 'Инсигния'],
    // CHEVROLET
    'niva' => ['niva', 'нива', 'Niva', 'Нива'],
    'cruze' => ['cruze', 'круз', 'Cruze', 'Круз'],
    'lacetti' => ['lacetti', 'лачетти', 'Lacetti', 'Лачетти'],
    // UAZ
    'patriot' => ['patriot', 'патриот', 'Patriot', 'Патриот'],
    'hunter' => ['hunter', 'хантер', 'Hunter', 'Хантер'],
    // GAZ
    'gazelle' => ['gazelle', 'газель', 'Gazelle', 'Газель'],
    'volga' => ['volga', 'волга', 'Volga', 'Волга'],
    // CHERY
    'tiggo' => ['tiggo', 'тигго', 'Tiggo', 'Тигго'],
    'bonus' => ['bonus', 'бонус', 'Bonus', 'Бонус'],
    // GEELY
    'atlas' => ['atlas', 'атлас', 'Atlas', 'Атлас'],
    'emgrand' => ['emgrand', 'эмгранд', 'Emgrand', 'Эмгранд'],
    // HAVAL
    'f7' => ['f7', 'F7', 'Ф7'],
    'jolion' => ['jolion', 'jolion', 'Джолион', 'Jolion'],
    // EXEED
    'txl' => ['txl', 'TXL', 'ТХЛ'],
    'vx' => ['vx', 'VX', 'ВХ'],
    // JAC
    's3' => ['s3', 'S3', 'С3'],
    's5' => ['s5', 'S5', 'С5'],
    // BYD
    'song' => ['song', 'Song', 'Сонг'],
    'tang' => ['tang', 'Tang', 'Танг'],
    // DONGFENG
    '580' => ['580', 'DFM 580', 'Dongfeng 580', 'Донгфенг 580'],
    // FAW
    'besturn' => ['besturn', 'Besturn', 'Бестурн'],
    // TATA
    'indica' => ['indica', 'Indica', 'Индика'],
    // PROTON
    'waja' => ['waja', 'Waja', 'Ваджа'],
    // TESLA
    'model 3' => ['model 3', 'модель 3', 'Model 3', 'Модель 3'],
    'model s' => ['model s', 'модель с', 'Model S', 'Модель С'],
    'model x' => ['model x', 'модель икс', 'Model X', 'Модель Икс'],
    'model y' => ['model y', 'модель у', 'Model Y', 'Модель У'],
    // FAW
    'Bestune' => ['Бестюн', 'Пездюн'],
];